on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  # to be able to trigger a manual build
  workflow_dispatch:

name: Render project

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.1"
          use-public-rspm: true

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: r-lib/actions/setup-renv@v2
          
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Render with Quarto
        shell: bash -l {0}  
        run: |
          source renv/python/virtualenvs/renv-python-3.10/bin/activate
          quarto render

      - name: Deploy to Netlify 🚀
        uses: data-intuitive/netlify-deploy-action@main
        if: github.event_name != 'pull_request'
        with:
          auth: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          site: ${{ secrets.NETLIFY_SITE_ID }}
          dir: '_site'
          prod: true
          message: 'Deploy production ${{ github.ref }}'

      - name: Deploy preview
        id: deploy_preview
        if: github.event_name == 'pull_request'
        uses: data-intuitive/netlify-deploy-action@main
        with:
          auth: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          site: ${{ secrets.NETLIFY_SITE_ID }}
          dir: '_site'
          alias: "${{ env.BRANCH_NAME }}"
          message: 'Deploy prooduction ${{ github.ref }}'

      - uses: thollander/actions-comment-pull-request@v2
        if: github.event_name == 'pull_request'
        with:
          message: |
            [![Deploy: success](https://img.shields.io/badge/Deploy-success-success)](${{ steps.deploy_preview.outputs.deploy-url }})
          comment_tag: deploy_status

      - uses: thollander/actions-comment-pull-request@v2
        if: github.event_name == 'pull_request' && failure()
        with:
          message: |
            [![Deploy: failure](https://img.shields.io/badge/Deploy-failure-critical)]${{ steps.deploy_preview.outputs.logs }})
          comment_tag: deploy_status

